name: Update Automation
on:
    schedule:
    - cron: "* 23 * * *"
    push:
        branches:
          - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
          
        - name: Fetch Upstream
          uses: bdougie/fetch-upstream@master
          with:
            upstream: manami-project/anime-offline-database
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}    

        - name: Publish to Dockerhub
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: luqmansen/hanako-mongodb
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
    sync_dockerhub_readme:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master

        - uses: meeDamian/sync-readme@v1.0.6
          with:
            pass: ${{ secrets.DOCKER_PASSWORD }}
            description: true

